Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the dataset

In [2]:
dataset = pd.read_csv('amazon_reviews_us_Electronics_v1_00.tsv',delimiter = '\t', quoting = 3,nrows=10000)
dataset2 = pd.read_csv('amazon_reviews_us_Apparel_v1_00.tsv',delimiter = '\t', quoting = 3,nrows=10000)
dataset = pd.concat([dataset,dataset2])
dataset = dataset.reset_index()

Stemming and removing the stop words

In [3]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(len(dataset)):
  review = re.sub('[^a-zA-z]',' ',str(dataset['review_body'][i])+' '+str(dataset['review_headline'][i]))
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/gauthammallipeddi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Bag of words

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=10000)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:,-8].values

In [5]:
print(len(X[0]))

10000


Training and testing split

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Feature selection

In [7]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

Classification

In [8]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 40,criterion='entropy')
classifier.fit(X_train, y_train)


RandomForestClassifier(criterion='entropy', n_estimators=40)

Predicting the test results

In [9]:
y_pred = classifier.predict(X_test)

In [10]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[5 5]
 [5 5]
 [5 5]
 ...
 [5 2]
 [5 4]
 [5 5]]


Accuracy score

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 337    4    4    8  122]
 [  50   54    2    6  100]
 [  34    4   79   11  165]
 [  10    0    2  182  382]
 [  12    1    6   11 2414]]


0.7665

In [12]:
def TodoFunction(new_review=-1):
    if(new_review==-1):
        new_review = inputtxt.get(1.0, "end-1c")
    new_review = new_review.lower()
    new_review = new_review.split()
    ps = PorterStemmer()
    all_stopwords = stopwords.words('english')
    all_stopwords.remove('not')
    new_review = [ps.stem(word) for word in new_review if not word in set(all_stopwords)]
    new_review = ' '.join(new_review)
    new_corpus = [new_review]
    print(new_corpus)
    new_X_test = cv.transform(new_corpus).toarray()
    print(new_X_test)
    new_y_pred = classifier.predict(new_X_test)
    print(new_y_pred)

GUI (Ignore the below cell on Google colab)

In [13]:
import tkinter as tk
frame = tk.Tk()
frame.title("Submit Your Review")
frame.geometry('400x200')
  

inputtxt = tk.Text(frame,height = 5,width = 20)
  
inputtxt.pack()

submitButton = tk.Button(frame,
                        text = "Submit", 
                        command = TodoFunction)
submitButton.pack()

lbl = tk.Label(frame, text = "")
lbl.pack()
frame.mainloop()

['good']
[[0 0 0 ... 0 0 0]]
[5]
['good']
[[0 0 0 ... 0 0 0]]
[5]


User input cell (Use this cell on Google colab)

In [16]:
new_review = input("Enter the review:")
TodoFunction(new_review)

Enter the review:Bad
['bad']
[[0 0 0 ... 0 0 0]]
[1]
